spring:
  application:
    name: CrudExample

  datasource:
    url: jdbc:mysql://${database_hostname}:${database_port}/${configuration_database_name}
    username: ${database_username}
    password: ${database_password}


    hikari:
      idleTimeout: 2400000
      maximumPoolSize: 5

  jpa:
    database: default
    show-sql: true
    
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

server:
  port: 8090